name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build the API Docker image
        run: docker build ./api --file ./api/Dockerfile.api --tag my-dockerhub-username/challenge-api:latest

      - name: Push the API Docker image
        run: docker push my-dockerhub-username/challenge-api:latest

  build-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build the Client Docker image
        run: docker build ./client --file ./client/Dockerfile.client --tag my-dockerhub-username/challenge-client:latest

      - name: Push the Client Docker image
        run: docker push my-dockerhub-username/challenge-client:latest
